### ISSUE TITLE
Water depletes extremely quickly.

### ISSUE THREAD

**Issue by Nathan22211** [ChocomintSSR/WildAdventure#4]
it was probably only 5-10 minutes into the game with this, and I end up taking damage from lack of water. Pretty sure it can take maybe 30-40 minutes to completely deplete food on normal?

Also end up dead from it on normal difficulty, should at least bring me down to half a heart or slightly more considering how fast it depletes

**Comment by ChocomintSSR** [comment]
Thanks for your advise!
I'll let foods can increase water in the next version and improve the damage system.
I'm sorry for bad game experiment!
