### ISSUE TITLE
Movable GUI | Stamina disappears

### ISSUE THREAD

**Issue by Parley1984** [ChocomintSSR/WildAdventure#5]
Hello.

First of all, thanks for this great mod. It's really fun. I have two things to say about it.

1. it would be wonderful if you could move the GUI objects. Otherwise it happens that they overlap with objects of other GUIs, which is of course unpleasant.

2. as soon as I take something offhand, the stamina bar disappears.

Thanks a lot

**Comment by ChocomintSSR** [comment]
Does the stamina bar means the horse's bar?

**Comment by Parley1984** [comment]
I mean the yellow bar that is inserted by the mod (see picture 1). As soon as you move something to the offhand, this bar disappears (see picture 2).

In addition, I noticed another error in connection with the mod AppleSkin. Due to the shifted HUD, the symbols of AppleSkin no longer fit with the hunger and life bar of Micecraft. They appear too far down. (see picture 3).

![Picture1](https://user-images.githubusercontent.com/93315522/179278440-be27e0d5-d11c-4fb0-af6d-258ccb79192f.png)
![Picture2](https://user-images.githubusercontent.com/93315522/179278451-25c9f6ef-57f5-477c-88bc-c9d8a986e271.png)
![Picture3](https://user-images.githubusercontent.com/93315522/179278457-aa9a99f3-14a7-483e-a709-81de3c155edb.png)

**Comment by ChocomintSSR** [comment]
@Parley1984 
Disappearing bar will be fix in the next version.
Second, due to the different system between my mod and apple skin, I'm still looking for the solution.
Sorry for bad playing experience!
