### ISSUE TITLE
Change "minecraft" value in Fabric.mod.json file from "1.19" to ">=1.19" or "1.19.2"

### ISSUE THREAD

**Issue by GermanArtur** [ChocomintSSR/WildAdventure#7]
![image](https://user-images.githubusercontent.com/64424996/190237010-e604e591-b875-4688-83e4-37fe4e439b35.png)
![image](https://user-images.githubusercontent.com/64424996/190237042-ccaa6fe2-7d81-4742-89a6-e6454bf5a12e.png)

**Comment by ChocomintSSR** [comment]
Does this affect mod loading?

**Comment by ChocomintSSR** [comment]
ok, I'll fix it ASAP.

**Comment by JustFoxx** [comment]
release it

**Comment by ChocomintTW** [comment]
https://github.com/ChocomintSSR/WildAdventure/releases/tag/1.19-v1.4.1
